#Application Configuration
server:
  port: 8095
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  # datasource:
  #   url: jdbc:mysql://localhost:3306/blogging
  #   username: root
  #   password: giansm1992

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        
springdoc:
  api-docs:
    path: /customersupport-api-docs
  swagger-ui: 
    path: /customersupport-api-docs-ui.html

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
