server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: customersupport-service
          uri: lb://customersupport-service
          predicates:
            - Path=/customersupports/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: collectivity-service
          uri: lb://collectivity-service
          predicates:
            - Path=/collectivities/**